# Basic Configuration
baseURL = 'https://agsamaniego.com/'
defaultContentLanguage = 'en'
languageCode = 'en-us'
title = 'A.G. Samaniego'
paginate = 10
timeZone = "America/New_York"

# Theme Configuration
theme = "terminal"

[pagination]
  pagerSize = 5

[params]
  # Content Configuration
  contentTypeName = "posts"
  showMenuItems = 3
  showLanguageSelector = false
  
  # Theme Layout
  fullWidthTheme = false
  centerTheme = false
  
  # Post Display Settings
  autoCover = true
  showLastUpdated = false
  updatedDatePrefix = "Updated"
  readingTime = true
  
  # Table of Contents
  toc = true
  tocTitle = "Table of Contents"
  
  # Date Format
  dateFormat = "2006-01-02"

[languages]
  [languages.en]
    languageName = "English"
    title = "A.G. Samaniego"
    weight = 1

    [languages.en.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = "A.G. Samaniego"
      keywords = "blog,developer,personal"
      copyright = "© 2025 A.G. Samaniego"
      description = "Personal website and blog of A.G. Samaniego"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "A.G. Samaniego 💎"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about-me"
          name = "About Me"
          url = "/about-me"
          weight = 1
        [[languages.en.menu.main]]
          identifier = "resume"
          name = "Resume"
          url = "/resume"
          weight = 2
        [[languages.en.menu.main]]
          identifier = "blog"
          name = "My Blog"
          url = "/blog"
          weight = 3